Controllers/ProductController.cs
using AdminApplication.Models;
using AdminApplication.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting.Internal;
using Project_C.Models;
using Project_C.Models.UserModels;
using Project_C.ViewModels;
using System.Collections.ObjectModel;
using System.Diagnostics;
using static System.Net.Mime.MediaTypeNames;

namespace Project_C.Controllers
{
    public class ProductController : Controller
    {
        private ApplicationDbContext _context;
        public List<string> places;

        public ProductController( ApplicationDbContext context)
        {
            _context = context;
            places = new List<string> { "Keuken", "Badkamer", "Woonkamer", "Slaapkamer", "Gezondheid", "Buiten" };
        }

        // This action method checks if an employee is logged in. If not, it redirects to the LoginPage.
        public RedirectToActionResult CheckLogin()
        {
            // If no employee is currently logged in, redirect to the LoginPage.
            if (!CurrentEmployee.IsLoggedIn())
            {
                return RedirectToAction("LoginPage", "Access");
            }

            // If an employee is logged in, return null.
            return null;
        }

        // This action method retrieves all products from the database and returns them in a view.
        public IActionResult ProductIndex()
        {
            // Check if an employee is logged in.
            CheckLogin();

            // Return the ProductIndex view with all products from the database.
            return View(_context.Products);
        }

        // This action method handles GET requests to the EditProduct endpoint.
        [HttpGet]
        public IActionResult EditProduct(Guid id)
        {
            // Check if an employee is logged in.
            CheckLogin();

            // Retrieve the product to be edited from the database.
            Product selectedProduct = _context.Products.Find(id);

            // Create a new ProductEditModel object with the properties of the selected product.
            ProductEditModel productEditViewModel = new ProductEditModel
            {
                Id = selectedProduct.Id,
                Name = selectedProduct.Name,
                Description = selectedProduct.Description,
                Price = selectedProduct.Price,
                Place = selectedProduct.Place,
                PlaceAsString = selectedProduct.PlaceAsString,
                VideoLink = selectedProduct.VideoLink
            };

            // Create a SelectList containing all possible values for the Place property and set the selected value to the current value of the selected product.
            ViewBag.Places = new SelectList(places, selectedProduct.PlaceAsString);

            // Return the EditProduct view with the ProductEditModel object.
            return View(productEditViewModel);
        }

        // This action method handles POST requests to the EditProduct endpoint.
        [HttpPost]
        public IActionResult EditProduct(ProductEditModel productChanges)
        {
            // Check if an employee is logged in.
            CheckLogin();

            // Retrieve the product to be updated from the database.
            Product productToBeUpdated = _context.Products.Find(productChanges.Id);

            // Update the product's Description and Price properties with the values from the form.
            productToBeUpdated.Description = productChanges.Description;
            productToBeUpdated.Price = productChanges.Price;

            // If the PlaceAsString property has changed, update the Place and PlaceAsString properties accordingly.
            if(productToBeUpdated.PlaceAsString != productChanges.PlaceAsString)
            {
                productToBeUpdated.PlaceAsString = productChanges.PlaceAsString;

                // Use a switch statement to set the Place property to the correct integer value based on the selected room.
                switch (productToBeUpdated.PlaceAsString)
                {
                    case "Keuken":
                        productToBeUpdated.Place = 1;
                        break;
                    case "Badkamer":
                        productToBeUpdated.Place = 2;
                        break;
                    case "Woonkamer":
                        productToBeUpdated.Place = 3;
                        break;
                    case "Slaapkamer":
                        productToBeUpdated.Place = 4;
                        break;
                    case "Gezondheid":
                        productToBeUpdated.Place = 5;
                        break;
                    case "Buiten":
                        productToBeUpdated.Place = 6;
                        break;
                }
            }

            // Update the product's Name property with the value from the form.
            productToBeUpdated.Name = productChanges.Name;

            // If the VideoLink property has changed, update it to the new link.
            if (productToBeUpdated.VideoLink != productChanges.VideoLink)
            {
                // Extract the video ID from the YouTube link and create a new embed link.
                productToBeUpdated.VideoLink = $"https://www.youtube.com/embed/{productChanges.VideoLink.Substring(32, 11)}";
            }

            // If a new photo has been uploaded, update the product's ProductImage property with the new image.
            if (productChanges.Photo != null)
            {
                productToBeUpdated.ProductImage = StoreController.ImagetoByte(productChanges.Photo);
            }

            // Save changes to the database and redirect to the ProductIndex page.
            _context.SaveChanges();
            return RedirectToAction("ProductIndex");
        }



        //Deletes the product and redirects to index after confirmation has been asked
        public IActionResult ConfirmDeleteProduct(Guid id)
        {
            CheckLogin();
            //finds the product in the database with the given id
            Product selectedProduct = _context.Products.Find(id);
            //removes the selected product from the database
            _context.Products.Remove(selectedProduct);
            //saves the changes to the database
            _context.SaveChanges();
            //redirects to the ProductIndex action in the same controller
            return RedirectToAction("ProductIndex");
        }

        public IActionResult ProductDetails(Guid id)
        {
            CheckLogin();
            if (id == null)
            {
                //returns 404 Not Found if the given id is null
                return NotFound();
            }

            //finds the product in the database with the given id
            var product = _context.Products.Find(id);
            if (product == null)
            {
                //returns 404 Not Found if the product with the given id is not found in the database
                return NotFound();
            }

            //returns the ProductDetails view with the found product as its model
            return View(product);
        }

        [HttpGet]
        public IActionResult AddProduct()
        {
            CheckLogin();
            //creates an empty ProductViewModel object as the model for the AddProduct view
            ProductViewModel model = new ProductViewModel();
            //returns the AddProduct view with the empty model
            return View(model);
        }

        //creates the product and adds to database 
        [HttpPost]
        public IActionResult AddProduct(ProductViewModel product)
        {
            CheckLogin();

            //populate empty Product object with the data from the ViewModel
            Product newProduct = new Product
            {
                Id = product.Id,
                Name = product.Name,
                Description = product.Description,
                Price = product.Price,
                PlaceAsString = product.PlaceAsString,
                ProductImage = StoreController.ImagetoByte(product.Photo),
                //to use an Iframe in html, an embedded link from youtube is needed. To get this link, the user has to under go a couple steps on youtube.
                //To simplify the process, we slice the video-ID at the correct position to create the correct embed link.
                VideoLink = $"https://www.youtube.com/embed/{product.VideoLink.Substring(32, 11)}",
                Stores = product.Stores != null ? ProcessChosenStores(product.Stores) : null
            };

            //set Product.Place to the corresponding Integer, so we can route all products of a room in UserApplication
            switch (newProduct.PlaceAsString)
            {
                case "Keuken":
                    newProduct.Place = 1;
                    break;
                case "Badkamer":
                    newProduct.Place = 2;
                    break;
                case "Woonkamer":
                    newProduct.Place = 3;
                    break;
                case "Slaapkamer":
                    newProduct.Place = 4;
                    break;
                case "Gezondheid":
                    newProduct.Place = 5;
                    break;
                case "Buiten":
                    newProduct.Place = 6;
                    break;
            }

            //add the new product to the database
            _context.Products.Add(newProduct);
            //saves the changes to the database
            _context.SaveChanges();
            //redirects to the ProductIndex action in the same controller
            return RedirectToAction("ProductIndex");

        }


        //returns an Icollection of stores, based on the Ids (GUID) from the dropdown menu in AddProduct.CSHTML

Controllers/StoreController.cs
using AdminApplication.Models;
using AdminApplication.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Project_C.Models;
using Project_C.Models.UserModels;
using Project_C.ViewModels;
using System.Diagnostics;
using static System.Net.Mime.MediaTypeNames;

namespace Project_C.Controllers
{
    public class StoreController : Controller
    {
        private ApplicationDbContext _context;

        public StoreController(ApplicationDbContext context)
        {
            _context = context;
        }

        public RedirectToActionResult CheckLogin()
        {
            // check if the user is logged in
            if (!CurrentEmployee.IsLoggedIn())
            {
                // if not, redirect to the login page
                return RedirectToAction("LoginPage", "Access");
            }
            // if user is logged in, return null
            return null;
        }

        public IActionResult StoreIndex()
        {
            // check if user is logged in
            CheckLogin();
            // retrieve all stores from the database and pass them to the view
            return View(_context.Stores);
        }

        [HttpGet]
        public IActionResult EditStore(Guid id)
        {
            // check if user is logged in
            CheckLogin();
            // retrieve the selected store from the database
            Store selectedStore = _context.Stores.Find(id);
            // create a view model to store the store's data for editing
            StoreEditModel StoreViewModel = new StoreEditModel
            {
                Id = id,
                Name = selectedStore.Name,
                SiteLink = selectedStore.SiteLink,
            };
            // pass the view model to the view for editing
            return View(StoreViewModel);
        }

        [HttpPost]
        public IActionResult EditStore(StoreEditModel storeChanges)
        {
            // check if user is logged in
            CheckLogin();
            // retrieve the store to be updated from the database
            Store storeToBeUpdated = _context.Stores.Find(storeChanges.Id);
            // update the store's properties with the new values from the view model
            storeToBeUpdated.SiteLink = storeChanges.SiteLink;
            storeToBeUpdated.Name = storeChanges.Name;
            // check if a new store logo file was uploaded, and update the store's logo if so
            if (storeChanges.LogoFile != null)
            {
                storeToBeUpdated.StoreLogo = ImagetoByte(storeChanges.LogoFile);
            }
            // save the changes to the database
            _context.SaveChanges();
            // redirect back to the StoreIndex page
            return RedirectToAction("StoreIndex");
        }

        [HttpGet]
        public IActionResult AddStore()
        {
            // check if user is logged in
            CheckLogin();
            // return the AddStore view
            return View();
        }

        [HttpPost]
        public IActionResult AddStore(StoreViewModel store)
        {
            // check if user is logged in
            CheckLogin();
            // create a new Store object and populate its properties with the values from the view model
            Store newStore = new Store
            {
                Id = store.Id,
                Name = store.Name,
                SiteLink = store.SiteLink,
                StoreLogo = ImagetoByte(store.LogoFile)
            };
            // add the new store to the database
            _context.Stores.Add(newStore);
            // save the changes to the database
            _context.SaveChanges();
            // redirect back to the StoreIndex page
            return RedirectToAction("StoreIndex");
        }


        // The ImagetoByte function takes an IFormFile object (a file that is uploaded) and converts it into a byte array.
        // A MemoryStream is used to read the data from the IFormFile and convert it into a byte array, which is returned.
        // This byte array is then saved into the database as a Blob and converted into an image in the Views.

        public static byte[] ImagetoByte(IFormFile logoFile)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                logoFile.CopyTo(ms);
                return ms.ToArray();
            }
        }


        // The StoreDetails action method displays the details of a store with the given id.
        // If no id is provided or if the store with the given id is not found, a 404 Not Found status code is returned.
        // Otherwise, the StoreDetails view is returned with the details of the store.
        public IActionResult StoreDetails(Guid id)
        {
            CheckLogin();
            if (id == null)
            {
                return NotFound();
            }

            var store = _context.Stores.Find(id);
            if (store == null)
            {
                return NotFound();
            }

            return View(store);
        }

        // The DeleteStore action method displays the selected store for confirmation of deletion.
        // If the store with the given id is not found, a 404 Not Found status code is returned.
        // Otherwise, the DeleteStore view is returned with the selected store.
        [HttpGet]
        public IActionResult DeleteStore(Guid id)
        {
            CheckLogin();
            Store selectedStore = _context.Stores.Find(id);
            return View(selectedStore);
        }

        // The ConfirmDeleteStore action method deletes the selected store after user confirmation and redirects to the StoreIndex view.
        // If the store with the given id is not found, no action is taken.
        // Otherwise, the store is removed from the database and the StoreIndex view is returned.
        [HttpPost, ActionName("DeleteStore")]
        public IActionResult ConfirmDeleteStore(Guid id)
        {
            CheckLogin();
            Store selectedStore = _context.Stores.Find(id);
            if (selectedStore != null)
            {
                _context.Stores.Remove(selectedStore);
                _context.SaveChanges();
            }
            return RedirectToAction("StoreIndex");
        }

    }
}

Views/Shared/_Layout.cshtml
@using Project_C.Models.UserModels;

@{
    bool IsLoggedIn = false;
    bool IsAdmin = false;


    if(Project_C.Models.UserModels.CurrentEmployee.currentEmployee != null)
    {
        IsLoggedIn = true;
        if (Project_C.Models.UserModels.CurrentEmployee.currentEmployee.IsAdmin == true)
        {
            IsAdmin = true;
        }
    }

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdminApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdminApplication.styles.css" asp-append-version="true" />
    @*   <link rel="stylesheet" href="~/css/adminhome.css"> *@
</head>
<body>
@*    @{
        if (IsLoggedIn)
        {
            <header>
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                    <div class="container-fluid">
                        <a class="navbar-brand" asp-area="" asp-controller="Access" asp-action="">
                            <img src="~/images/Sol.png" width="90" height="40"/>
                        </a>

                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1">
                     
                                   
                                    
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="ProductIndex">Producten</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="StoreIndex">Winkels</a>
                                        </li>
                               @{
                                        if (IsAdmin)
                                        {
                                            <li class="nav-item">
                                                <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="EmployeeIndex">Medewerkers</a>
                                                                                        </li>
                                    }
                                }
                                <li class="nav-item my-2 my-lg-0">
                                                              
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Access" asp-action="Logout">Uitloggen</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Access" asp-action="AccountOverview">Welkom terug @CurrentEmployee.currentEmployee.Email !</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>
        }
    }

    *@

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>