Models/UserModels/Employee.cs
using System.ComponentModel.DataAnnotations;

namespace Project_C.Models.UserModels
{
    public class Employee
    {
        public Guid Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public bool IsAdmin { get; set; }

    }
}

Controllers/AccessController.cs
using AdminApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Project_C.Models.UserModels;

namespace Project_C.Controllers
{
    public class AccessController : Controller
    {
        private ApplicationDbContext _context;

        
        public AccessController(ApplicationDbContext context)
        {
            _context = context;
        }

    // This action method handles GET requests to the LoginPage endpoint.
    [HttpGet]
    public IActionResult LoginPage()
    {
        // Returns the Login view.
        return View();
    }

    // This action method handles GET requests to the HomePage endpoint.
    public IActionResult HomePage() 
    { 
        // Returns the Home view.
        return View(); 
    }

    // This action method handles POST requests to the LoginPage endpoint.
    [HttpPost]
    public IActionResult LoginPage(LoginCredentials logintry)
    {
        // Retrieves an employee from the database based on their email address.
        var employee = _context.Employees.FirstOrDefault(x => x.Email == logintry.Email);

        // If no employee is found, redirect back to the LoginPage.
        if (employee == null)
        {
            return RedirectToAction("LoginPage");
        }

        // If the employee's password matches the provided password and their email matches the provided email,
        // set the currentEmployee property to the retrieved employee and redirect to the HomePage.
        if (employee.Password == logintry.Password && employee.Email == logintry.Email)
        {
            CurrentEmployee.currentEmployee = employee;
            return RedirectToAction("HomePage");
        }

        // If the provided email and password do not match any employee in the database, redirect back to the LoginPage.
        return RedirectToAction("LoginPage");
    }

    // This action method handles GET requests to the Logout endpoint.
    public IActionResult Logout()
    {
        // Set the currentEmployee property to null and redirect to the LoginPage.
        CurrentEmployee.currentEmployee = null;
        return RedirectToAction("LoginPage");
    }

    }
}

Controllers/EmployeeController.cs
using AdminApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Project_C.Models.UserModels;
using Project_C.ViewModels;

namespace Project_C.Controllers
{
    public class EmployeeController : Controller
    {
        private ApplicationDbContext _context;
        public EmployeeController(ApplicationDbContext context) { 
            _context= context;
        }

        public RedirectToActionResult CheckLogin()
        {
            //if (!CurrentEmployee.IsLoggedIn())
            //{
            //    return RedirectToAction("LoginPage", "Access");
            //}
            //if (!CurrentEmployee.IsAdmin())
            //{
            //    return RedirectToAction("HomePage", "Access");
            //}
            return null;
        }

        // Controller action for the employee index page
        public IActionResult EmployeeIndex()
        {
            CheckLogin(); // Check if the user is logged in
            return View(_context.Employees); // Display a view of all employees
        }

        // Controller action for the add employee page (HTTP GET)
        [HttpGet]
        public IActionResult AddEmployee()
        {
            CheckLogin(); // Check if the user is logged in
            return View(); // Display a view for adding a new employee
        }

        // Controller action for adding a new employee to the database (HTTP POST)
        [HttpPost]
        public IActionResult AddEmployee(EmployeeCreateModel newEmployeemodel)
        {
            CheckLogin(); // Check if the user is logged in
            if (ModelState.IsValid) // Check if the data model is valid
            {
                // Create a new employee object with the data from the form
                Employee newEmployee = new Employee()
                {
                    Id = Guid.NewGuid(),
                    Username = newEmployeemodel.Username,
                    Password = newEmployeemodel.Password,
                    Email = newEmployeemodel.Email,
                    IsAdmin = newEmployeemodel.IsAdmin == "Administrator" ? true : false
                };

                // Add the new employee to the database and save changes
                _context.Employees.Add(newEmployee);
                _context.SaveChanges();
            }

            // Redirect to the employee index page
            return RedirectToAction("EmployeeIndex");
        }

        // Controller action for the employee details page
        public IActionResult EmployeeDetails(Guid id)
        {
            CheckLogin(); // Check if the user is logged in
            var currentEmployee = _context.Employees.Find(id); // Find the employee with the specified ID
            if (currentEmployee == null) // If the employee doesn't exist, return a 404 error
            {
                return NotFound();
            }

            // Display a view of the employee's details
            return View(currentEmployee);
        }

        // Controller action for the delete employee page (HTTP GET)
        [HttpGet]
        public IActionResult DeleteEmployee(Guid id)
        {
            CheckLogin(); // Check if the user is logged in
            return View(_context.Employees.Find(id)); // Display a view for deleting the specified employee
        }

        // Controller action for deleting an employee from the database (HTTP POST)
        [HttpPost, ActionName("DeleteEmployee")]
        public IActionResult ConfirmDeleteEmployee(Guid id)
        {
            CheckLogin(); // Check if the user is logged in
            _context.Employees.Remove(_context.Employees.Find(id)); // Remove the employee with the specified ID from the database
            _context.SaveChanges(); // Save changes to the database
            return RedirectToAction("EmployeeIndex"); // Redirect to the employee index page
        }



        // Finds the employee with the specified id and creates a new EmployeeCreateModel based on it, 
        // which will be used to modify the employee.
        [HttpGet]
        public IActionResult EditEmployee(Guid id)
        {
            CheckLogin();
            // Find employee by id.
            Employee currentEmployee = _context.Employees.Find(id);

            // Create new EmployeeCreateModel with data from current employee.
            EmployeeCreateModel employeeCreateModel = new EmployeeCreateModel()
            {
                Id = currentEmployee.Id,
                Username = currentEmployee.Username,
                Password = currentEmployee.Password,
                Email = currentEmployee.Email,
                IsAdmin = currentEmployee.IsAdmin == true ? "Administrator" : "Medewerker"
            };

            // Return the view with the new EmployeeCreateModel.
            return View(employeeCreateModel);
        }


        // Updates the employee with the data from the submitted EmployeeCreateModel.
        [HttpPost]
        public IActionResult EditEmployee(EmployeeCreateModel employeechanges)
        {
            CheckLogin();
            if (ModelState.IsValid)
            {
                // Find employee in database by id.
                Employee employeeToBeUpdated = _context.Employees.Find(employeechanges.Id);

                // Modify the employee with the data from the submitted EmployeeCreateModel.
                employeeToBeUpdated.Username = employeechanges.Username;
                employeeToBeUpdated.Password = employeechanges.Password;
                employeeToBeUpdated.Email = employeechanges.Email;
                employeeToBeUpdated.IsAdmin = employeechanges.IsAdmin == "Administrator" ? true : false;

                // Save the changes to the employee record in the database.
                _context.SaveChanges();

                // Redirect to the EmployeeIndex page.
                return RedirectToAction("EmployeeIndex");
            }

            // If ModelState is not valid, redirect to the EmployeeIndex page.
            return RedirectToAction("EmployeeIndex");
        }

    }
}

Views/Employee/AddEmployee.cshtml
@model Project_C.ViewModels.EmployeeCreateModel

@{
    ViewData["Title"] = "Add Employee";
}

<h1>Nieuwe Werknemer</h1>

<style>
    * {
        box-sizing: border-box;
    }

    .row {
        margin-left: -5px;
        margin-right: -5px;
    }

    .column {
        float: left;
        width: 50%;
        padding: 5px;
    }

    .row::after {
        content: "";
        clear: both;
        display: table;
    }

    table {
        border-collapse: collapse;
        border-spacing: 0;
        width: 100%;
        border: 1px solid #ddd;
    }

    th, td {
        text-align: left;
        padding: 16px;
    }

    th {
        background-color: #f2f2f2;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    .PropertyName {
        font-family: Arial;
        font-size: 25px;
    }

    .DetailInfo {
        font-family: Arial;
        font-size: 18px;
    }
</style>


<div class="row">
    <form method="post" enctype="multipart/form-data" asp-action="AddEmployee" asp-controller="Employee">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="column">
            <table class="CostumMadeTable">
                <thead>
                    <tr>
                        <th><h2>Details</h2></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="PropertyName">Gebruikersnaam</td>
                    </tr>
                    <tr>
                        <td class="DetailInfo">
                            <input asp-for="Username" class="form-control" />
                            <span asp-validation-for="Username" class="text-danger"></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="PropertyName">
                            Wachtwoord
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input asp-for="Password" class="form-control" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </td>
                    </tr>
                                        <tr>
                        <td class="PropertyName">
                            E-mail
                        </td>
                    </tr>
                    <tr>
                        <td>
                      <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
                    </td>
                    </tr>
                                                            <tr>
                        <td class="PropertyName">
                            Rol
                        </td>
                    </tr>
                    <tr>
                        <td>
                <select asp-for=IsAdmin type="text" class="form-control" />
                            <option value="Administrator">Administrator</option>
                        <option value="Medewerker">Medewerker</option>
                <span asp-validation-for="IsAdmin" class="text-danger"></span>
                </td>
                    </tr>


                </tbody>
            </table>
            <input type="submit" value="Toevoegen" class="btn btn-success" />
            <a class="btn btn-primary" asp-controller="Employee" asp-action="EmployeeIndex">Terug</a>
        </div>

    


    </form>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Views/Employee/DeleteEmployee.cshtml
@model Project_C.Models.UserModels.Employee

@{

    ViewData["Title"] = "Delete Employee";
}
<h4>Weet u zeker dat u "@Model.Username" wilt verwijderen? 
    (ID: @Model.Id)
    </h4>


<form asp-action="DeleteEmployee">
    <input type="hidden" asp-for="Id" />
    <input type="submit" value="Delete" class="btn btn-danger" />
    <a class="btn btn-primary" asp-action="EmployeeDetails" asp-route-id="@Model.Id">Back</a>
</form>

Views/Employee/EditEmployee.cshtml
@model Project_C.ViewModels.EmployeeCreateModel
@{

    ViewData["Title"] = "Edit Employee";
}

<h1>Bewerk - @Model.Username's Account</h1>

<style>
    * {
        box-sizing: border-box;
    }

    .row {
        margin-left: -5px;
        margin-right: -5px;
    }

    .column {
        float: left;
        width: 50%;
        padding: 5px;
    }

    .row::after {
        content: "";
        clear: both;
        display: table;
    }

    table {
        border-collapse: collapse;
        border-spacing: 0;
        width: 100%;
        border: 1px solid #ddd;
        border-collapse: collapse;
    top: 150px;
    left: 120px;
    position: absolute;
    margin: 12px 0;
    border-spacing: 2px;
    border-radius: 12px 12px 0 0;
    box-shadow: 0 2px 12px rgba(32,32,32,.5);
    background: white;
    border-spacing: 20px;

    }

    td, tr {
        width: 10px;
        height: 60px;
    }

    .table {
        width: 1600px;
        border-spacing: 20px;
    }

    thead {
        font-size: 23px;
        background-color: #deae62;
        color: #ffffff;
        text-align: left;
    }

    th {
        background-color: #f2f2f2;
    }

    tr:nth-child(even) {
        background-color: #f2f2f2;
    }

    .table tbody tr {
        border-bottom: 1px solid #dddddd;
    }

        .table tbody tr:nth-of-type(even) {
            background-color: #f3f3f3;
        }

        .table tbody tr:last-of-type {
            border-bottom: 8px solid #deae62;
        }

    .PropertyName {
        font-family: Arial;
        font-size: 25px;
    }

    .DetailInfo {
        font-family: Arial;
        font-size: 18px;
    }

    h1 {
        position: absolute;
        left: 700px;
        top: 60px;
        font-family: 'Times New Roman';
    }
    .btn.btn-bewerk {
    position: absolute;
    height: 40px;
    width: 160px;
    right: 950px;
    top: 100px;
    background: rgba(0, 100, 200);
    border: 0px #f8dd85;
    color: black;
    text-align: center;
    place-content: center;
    place-content: center;
    align-items: center;
    font-size: 22px;
    border-radius: 0px;
    cursor: pointer;
    line-height: 35px;
    transition: .5s;
    font-size: medium;
    border: 0;
    box-shadow: #ffffff 0 -25px 18px -14px inset,rgba(4, 187, 99, .15) 0 1px 1px,#f3f3f3 0 2px 4px,black 0 4px 8px,#f3f3f3 0 8px 16px,rgba(44, 187, 99, .15) 0 16px 32px;
        }
    .btn.btn-terug

    {
        position: absolute;
        height: 40px;
        width: 100px;
        right: 820px;
        top: 110px;
        background: rgba(200, 20, 0);
        border: 0px #f8dd85;
        color: black;
        text-align: center;
        place-content: center;
        place-content: center;
        align-items: center;
        font-size: 22px;
        border-radius: 0px;
        cursor: pointer;
        line-height: 35px;
        transition: .5s;
        font-size: medium;
        border: 0;
        box-shadow: #ffffff 0 -25px 18px -14px inset,rgba(4, 187, 99, .15) 0 1px 1px,#f3f3f3 0 2px 1px,black 0 4px 8px,#f3f3f3 0 8px 16px,rgba(44, 187, 99, .15) 0 16px 32px;
    }
</style>


<div class="row">
    <form method="post" enctype="multipart/form-data" asp-action="EditEmployee" asp-controller="Employee">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="column">
            <table class="table">
                <thead>
                    <tr>
                        <th><h2>Details</h2></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="PropertyName">Gebruikersnaam</td>
                    </tr>
                    <tr>
                        <td class="DetailInfo">
                            <input asp-for="Username" class="form-control" />
                            <span asp-validation-for="Username" class="text-danger"></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="PropertyName">
                            Wachtwoord
                        </td>
                    </tr>
                    <tr>
                        <td class="DetailInfo">
                            <input asp-for="Password" class="form-control" />
                            <span asp-validation-for="Password" class="text-danger"></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="PropertyName">
                            E-mail
                        </td>
                    </tr>
                    <tr>
                        <td class="DetailInfo">
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </td>
                    </tr>
                    <tr>
                        <td class="PropertyName">
                            Rol
                        </td>
                    </tr>
                    <tr>
                        <td class="DetailInfo">
                            <select asp-for=IsAdmin type="text" class="form-control" />
                            <option value="Administrator">Administrator</option>
                            <option value="Medewerker">Medewerker</option>
                            <span asp-validation-for="IsAdmin" class="text-danger"></span>
                        </td>
                    </tr>


                </tbody>
            </table>
            <input type="submit" value="Bijwerken voltooien" class="btn btn-bewerk" />
            <a class="btn btn-terug" asp-controller="Employee" asp-action="EmployeeIndex">Terug</a>
        </div>

    </form>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

Views/Employee/EmployeeDetails.cshtml
@model Project_C.Models.UserModels.Employee
@{
    string isadmin = Model.IsAdmin == true ? "Administrator" : "Medewerker";
}
<link rel="stylesheet" href="~/css/employeedetails.css"/>     
<table class="table">
    <thead>
        <tr>
            <th><h2>Details</h2></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="PropertyName">Id</td>
        </tr>
        <tr>
            <td class="DetailInfo">@Model.Id</td>
        </tr>
        <tr>
            <td class="PropertyName">Gebruikersnaam</td>
        </tr>
        <tr>
            <td class="DetailInfo">@Model.Username</td>
        </tr>
        <tr>
            <td class="PropertyName">Wachtwoord</td>
        </tr>
        <tr>
            <td class="DetailInfo">@Model.Password</td>
        </tr>
        <tr>
            <td class="PropertyName">E-mail</td>
        </tr>
        <tr>
            <td class="DetailInfo">@Model.Email</td>
        </tr>
        <tr>
            <td class="PropertyName">Bevoegheden</td>
        </tr>
        <tr>
            <td class="DetailInfo">@isadmin</td>
        </tr>
        <tr>
            <td>
                 <a asp-action="HomePage" asp-controller="Access" class="Teruggaan">
                            <span class="icon">
                                <ion-icon name="return-up-back-sharp"></ion-icon>
                            </span>
                            <span class="text">Thuispagina</span>
                        </a>

                <a class="btn btn-bewerk" asp-action="EditEmployee" asp-route-id="@Model.Id">Bewerk</a>
                <a class="btn btn-verwijder" asp-action="DeleteEmployee" asp-route-id="@Model.Id">Verwijder Account</a>
                                                <div class="center">
                                <input type="checkbox" id="click">
                                <label for="click" class="click-me">Verwijder Account</label> 
                                    <div class="content">
        <label for="click" class="fas fa-check"></label>
        <p>
            Weet u zeker dat u "@Model.Username" wilt verwijderen? <br>
            (ID: @Model.Id)
        </p>
        <form asp-action="DeleteEmployee">
            <div class="btn-pop up">
                <input type="hidden" asp-for="@Model.Id" />
                <input type="submit" value="Definitief Verwijderen" class="btn btn-defverwijder" />
                <a class="backbutton" asp-action="EmployeeDetails" asp-route-id="@Model.Id">Ga Terug</a>
            </div>
        </form>
        <div class="line"></div>
        <a asp-action="Startpagina" asp-controller="Application" class="close-btn">
        </a>
    </div>
                           </div>

            </td>
        
        </tr>
         <wow>
            <div class="navigation">
                <ul>
                                                    <terug>
                    <a asp-action="HomePage" asp-controller="Access" class="Teruggaan">
                                        <span class="icon">
                                <ion-icon name="return-up-back-sharp"></ion-icon>
                        </span>
                            <span class="text">Thuispagina</span>
                            </a>
                    </terug>
                </ul>
                    </div>
                    </wow>
    </tbody>
</table>

<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

Views/Employee/EmployeeIndex.cshtml
@model IEnumerable<Project_C.Models.UserModels.Employee>
@using Project_C.Models.UserModels;

@{
    bool IsLoggedIn = false;
    bool IsAdmin = false;


    if(Project_C.Models.UserModels.CurrentEmployee.currentEmployee != null)
    {
        IsLoggedIn = true;
        if (Project_C.Models.UserModels.CurrentEmployee.currentEmployee.IsAdmin == true)
        {
            IsAdmin = true;
        }
    }
    }
@{
    ViewData["Title"] = "Index";
}

<h1>Werknemers</h1>

<link rel="stylesheet" href="~/css/medewerkerpagina.css">

<a asp-controller="Employee" asp-action="AddEmployee"><input class="btn btn-success" value="Nieuwe werknemer" /></a>
<style>
    table {
        border-collapse: collapse;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>

<table class="table">
    <thead>
        <tr>
            <th style="width:20%">
                Gebruikersnaam
            </th>
            <th style="width:25%">
                E-mail
            </th>
            <th>
                Id
            </th>
            <th>
                Rol
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            string rol = item.IsAdmin == true ? "Administrator" : "Medewerker";
            <tr>
                <td>
                    @item.Username
                </td>
                <td>
                    @item.Email
                </td>
                <td>
                    @item.Id
                </td>
                <td>
                    @rol
                </td>
                <td>
                    <form asp-action="View">
                        <div class="btn-group">
                            <a class="btn btn-bekijk" asp-action="EmployeeDetails" asp-route-id="@item.Id">Bekijk</a>
                            <a class="btn btn-bewerk" asp-action="EditEmployee" asp-route-id="@item.Id">Bewerk</a>
                        </div>
                    </form>
                </td>
            </tr>
        }
        

        <wow>
            <div class="navigation">
                <ul>
                                                    <terug>
                    <a asp-action="HomePage" asp-controller="Access" class="Teruggaan">
                                        <span class="icon">
                                <ion-icon name="return-up-back-sharp"></ion-icon>
                        </span>
                            <span class="text">Thuispagina</span>
                            </a>
                    </terug>
                    <lit>
                    <a asp-action="Logout" asp-controller="Access" class="Uitloggen">
                        
                        <span class="icon">
                            <ion-icon name="log-out-sharp"></ion-icon>
                        </span>
                            <span class="text">Uitloggen</span>

                        </a>
                    </lit>
                    <div class="index"></div>
                </ul>
            </div>
            <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
            <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
            </>
        </wow>
    </tbody>
</table>