Controllers/AccessController.cs
using AdminApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Project_C.Models.UserModels;

namespace Project_C.Controllers
{
    public class AccessController : Controller
    {
        private ApplicationDbContext _context;

        
        public AccessController(ApplicationDbContext context)
        {
            _context = context;
        }

    // This action method handles GET requests to the LoginPage endpoint.
    [HttpGet]
    public IActionResult LoginPage()
    {
        // Returns the Login view.
        return View();
    }

    // This action method handles GET requests to the HomePage endpoint.
    public IActionResult HomePage() 
    { 
        // Returns the Home view.
        return View(); 
    }

    // This action method handles POST requests to the LoginPage endpoint.
    [HttpPost]
    public IActionResult LoginPage(LoginCredentials logintry)
    {
        // Retrieves an employee from the database based on their email address.
        var employee = _context.Employees.FirstOrDefault(x => x.Email == logintry.Email);

        // If no employee is found, redirect back to the LoginPage.
        if (employee == null)
        {
            return RedirectToAction("LoginPage");
        }

        // If the employee's password matches the provided password and their email matches the provided email,
        // set the currentEmployee property to the retrieved employee and redirect to the HomePage.
        if (employee.Password == logintry.Password && employee.Email == logintry.Email)
        {
            CurrentEmployee.currentEmployee = employee;
            return RedirectToAction("HomePage");
        }

        // If the provided email and password do not match any employee in the database, redirect back to the LoginPage.
        return RedirectToAction("LoginPage");
    }

    // This action method handles GET requests to the Logout endpoint.
    public IActionResult Logout()
    {
        // Set the currentEmployee property to null and redirect to the LoginPage.
        CurrentEmployee.currentEmployee = null;
        return RedirectToAction("LoginPage");
    }

    }
}

Controllers/EmployeeController.cs
using AdminApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Project_C.Models.UserModels;
using Project_C.ViewModels;

namespace Project_C.Controllers
{
    public class EmployeeController : Controller
    {
        private ApplicationDbContext _context;
        public EmployeeController(ApplicationDbContext context) { 
            _context= context;
        }

        public RedirectToActionResult CheckLogin()
        {
            //if (!CurrentEmployee.IsLoggedIn())
            //{
            //    return RedirectToAction("LoginPage", "Access");
            //}
            //if (!CurrentEmployee.IsAdmin())
            //{
            //    return RedirectToAction("HomePage", "Access");
            //}
            return null;
        }

        // Controller action for the employee index page
        public IActionResult EmployeeIndex()
        {
            CheckLogin(); // Check if the user is logged in
            return View(_context.Employees); // Display a view of all employees
        }

        // Controller action for the add employee page (HTTP GET)
        [HttpGet]
        public IActionResult AddEmployee()
        {
            CheckLogin(); // Check if the user is logged in
            return View(); // Display a view for adding a new employee
        }

        // Controller action for adding a new employee to the database (HTTP POST)
        [HttpPost]
        public IActionResult AddEmployee(EmployeeCreateModel newEmployeemodel)
        {
            CheckLogin(); // Check if the user is logged in
            if (ModelState.IsValid) // Check if the data model is valid
            {
                // Create a new employee object with the data from the form
                Employee newEmployee = new Employee()
                {
                    Id = Guid.NewGuid(),
                    Username = newEmployeemodel.Username,
                    Password = newEmployeemodel.Password,
                    Email = newEmployeemodel.Email,
                    IsAdmin = newEmployeemodel.IsAdmin == "Administrator" ? true : false
                };

                // Add the new employee to the database and save changes
                _context.Employees.Add(newEmployee);
                _context.SaveChanges();
            }

            // Redirect to the employee index page
            return RedirectToAction("EmployeeIndex");
        }

        // Controller action for the employee details page
        public IActionResult EmployeeDetails(Guid id)
        {
            CheckLogin(); // Check if the user is logged in
            var currentEmployee = _context.Employees.Find(id); // Find the employee with the specified ID
            if (currentEmployee == null) // If the employee doesn't exist, return a 404 error
            {
                return NotFound();
            }

            // Display a view of the employee's details
            return View(currentEmployee);
        }

        // Controller action for the delete employee page (HTTP GET)
        [HttpGet]
        public IActionResult DeleteEmployee(Guid id)
        {
            CheckLogin(); // Check if the user is logged in
            return View(_context.Employees.Find(id)); // Display a view for deleting the specified employee
        }

        // Controller action for deleting an employee from the database (HTTP POST)
        [HttpPost, ActionName("DeleteEmployee")]
        public IActionResult ConfirmDeleteEmployee(Guid id)
        {
            CheckLogin(); // Check if the user is logged in
            _context.Employees.Remove(_context.Employees.Find(id)); // Remove the employee with the specified ID from the database
            _context.SaveChanges(); // Save changes to the database
            return RedirectToAction("EmployeeIndex"); // Redirect to the employee index page
        }



        // Finds the employee with the specified id and creates a new EmployeeCreateModel based on it, 
        // which will be used to modify the employee.
        [HttpGet]
        public IActionResult EditEmployee(Guid id)
        {
            CheckLogin();
            // Find employee by id.
            Employee currentEmployee = _context.Employees.Find(id);

            // Create new EmployeeCreateModel with data from current employee.
            EmployeeCreateModel employeeCreateModel = new EmployeeCreateModel()
            {
                Id = currentEmployee.Id,
                Username = currentEmployee.Username,
                Password = currentEmployee.Password,
                Email = currentEmployee.Email,
                IsAdmin = currentEmployee.IsAdmin == true ? "Administrator" : "Medewerker"
            };

            // Return the view with the new EmployeeCreateModel.
            return View(employeeCreateModel);
        }


        // Updates the employee with the data from the submitted EmployeeCreateModel.
        [HttpPost]
        public IActionResult EditEmployee(EmployeeCreateModel employeechanges)
        {
            CheckLogin();
            if (ModelState.IsValid)
            {
                // Find employee in database by id.
                Employee employeeToBeUpdated = _context.Employees.Find(employeechanges.Id);

                // Modify the employee with the data from the submitted EmployeeCreateModel.
                employeeToBeUpdated.Username = employeechanges.Username;
                employeeToBeUpdated.Password = employeechanges.Password;
                employeeToBeUpdated.Email = employeechanges.Email;
                employeeToBeUpdated.IsAdmin = employeechanges.IsAdmin == "Administrator" ? true : false;

                // Save the changes to the employee record in the database.
                _context.SaveChanges();

                // Redirect to the EmployeeIndex page.
                return RedirectToAction("EmployeeIndex");
            }

            // If ModelState is not valid, redirect to the EmployeeIndex page.
            return RedirectToAction("EmployeeIndex");
        }

    }
}

Controllers/MessageController.cs
using AdminApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Project_C.Models.UserModels;

namespace Project_C.Controllers
{
    public class MessageController : Controller
    {
        private ApplicationDbContext _context;

        public MessageController(ApplicationDbContext context)
        {
            _context = context;
        }

        // This function checks if the user is logged in, and redirects them to the login page if they are not
        public RedirectToActionResult CheckLogin()
        {
            if (!CurrentEmployee.IsLoggedIn())
            {
                return RedirectToAction("LoginPage", "Access");
            }
            return null;
        }

        // This function loads all messages and orders them by unanswered first, and displays them in the MessageIndex view
        public IActionResult MessageIndex()
        {
            CheckLogin();
            var allMessages = _context.Messages;
            return View(allMessages.OrderBy(x => x.IsAnswered));
        }

        // This function displays a specific message by ID in the MessageDetails view
        public IActionResult MessageDetails(Guid id)
        {
            CheckLogin();
            return View(_context.Messages.Find(id));
        }

        // This function sets the IsAnswered property of a message to true, adds the name of the employee who answered it, and saves it to the database
        public IActionResult AnswerMessage(Guid id)
        {
            CheckLogin();
            var Message = _context.Messages.Find(id);
            Message.IsAnswered = true;
            Message.EmployeeId = CurrentEmployee.currentEmployee.Id;
            Message.EmployeeName = CurrentEmployee.currentEmployee.Username;
            _context.SaveChanges();
            return RedirectToAction("MessageDetails", new { id = id });
        }

        // This function displays the DeleteMessage view for a specific message by ID
        [HttpGet]
        public IActionResult DeleteMessage(Guid id)
        {
            CheckLogin();
            return View(id);
        }

        // This function deletes a specific message by ID from the database
        [HttpPost, ActionName("DeleteMessage")]
        public IActionResult ConfirmDeleteMessage(Guid id)
        {
            CheckLogin();
            // Delete the message from the database
            _context.Messages.Remove(_context.Messages.Find(id));
            _context.SaveChanges();

            // Redirect to the MessageIndex page
            return RedirectToAction("MessageIndex");
        }

    }
}

Controllers/StoreController.cs
using AdminApplication.Models;
using AdminApplication.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Project_C.Models;
using Project_C.Models.UserModels;
using Project_C.ViewModels;
using System.Diagnostics;
using static System.Net.Mime.MediaTypeNames;

namespace Project_C.Controllers
{
    public class StoreController : Controller
    {
        private ApplicationDbContext _context;

        public StoreController(ApplicationDbContext context)
        {
            _context = context;
        }

        public RedirectToActionResult CheckLogin()
        {
            // check if the user is logged in
            if (!CurrentEmployee.IsLoggedIn())
            {
                // if not, redirect to the login page
                return RedirectToAction("LoginPage", "Access");
            }
            // if user is logged in, return null
            return null;
        }

        public IActionResult StoreIndex()
        {
            // check if user is logged in
            CheckLogin();
            // retrieve all stores from the database and pass them to the view
            return View(_context.Stores);
        }

        [HttpGet]
        public IActionResult EditStore(Guid id)
        {
            // check if user is logged in
            CheckLogin();
            // retrieve the selected store from the database
            Store selectedStore = _context.Stores.Find(id);
            // create a view model to store the store's data for editing
            StoreEditModel StoreViewModel = new StoreEditModel
            {
                Id = id,
                Name = selectedStore.Name,
                SiteLink = selectedStore.SiteLink,
            };
            // pass the view model to the view for editing
            return View(StoreViewModel);
        }

        [HttpPost]
        public IActionResult EditStore(StoreEditModel storeChanges)
        {
            // check if user is logged in
            CheckLogin();
            // retrieve the store to be updated from the database
            Store storeToBeUpdated = _context.Stores.Find(storeChanges.Id);
            // update the store's properties with the new values from the view model
            storeToBeUpdated.SiteLink = storeChanges.SiteLink;
            storeToBeUpdated.Name = storeChanges.Name;
            // check if a new store logo file was uploaded, and update the store's logo if so
            if (storeChanges.LogoFile != null)
            {
                storeToBeUpdated.StoreLogo = ImagetoByte(storeChanges.LogoFile);
            }
            // save the changes to the database
            _context.SaveChanges();
            // redirect back to the StoreIndex page
            return RedirectToAction("StoreIndex");
        }

        [HttpGet]
        public IActionResult AddStore()
        {
            // check if user is logged in
            CheckLogin();
            // return the AddStore view
            return View();
        }

        [HttpPost]
        public IActionResult AddStore(StoreViewModel store)
        {
            // check if user is logged in
            CheckLogin();
            // create a new Store object and populate its properties with the values from the view model
            Store newStore = new Store
            {
                Id = store.Id,
                Name = store.Name,
                SiteLink = store.SiteLink,
                StoreLogo = ImagetoByte(store.LogoFile)
            };
            // add the new store to the database
            _context.Stores.Add(newStore);
            // save the changes to the database
            _context.SaveChanges();
            // redirect back to the StoreIndex page
            return RedirectToAction("StoreIndex");
        }


        // The ImagetoByte function takes an IFormFile object (a file that is uploaded) and converts it into a byte array.
        // A MemoryStream is used to read the data from the IFormFile and convert it into a byte array, which is returned.
        // This byte array is then saved into the database as a Blob and converted into an image in the Views.

        public static byte[] ImagetoByte(IFormFile logoFile)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                logoFile.CopyTo(ms);
                return ms.ToArray();
            }
        }


        // The StoreDetails action method displays the details of a store with the given id.
        // If no id is provided or if the store with the given id is not found, a 404 Not Found status code is returned.
        // Otherwise, the StoreDetails view is returned with the details of the store.
        public IActionResult StoreDetails(Guid id)
        {
            CheckLogin();
            if (id == null)
            {
                return NotFound();
            }

            var store = _context.Stores.Find(id);
            if (store == null)
            {
                return NotFound();
            }

            return View(store);
        }

        // The DeleteStore action method displays the selected store for confirmation of deletion.
        // If the store with the given id is not found, a 404 Not Found status code is returned.
        // Otherwise, the DeleteStore view is returned with the selected store.
        [HttpGet]
        public IActionResult DeleteStore(Guid id)
        {
            CheckLogin();
            Store selectedStore = _context.Stores.Find(id);
            return View(selectedStore);
        }

        // The ConfirmDeleteStore action method deletes the selected store after user confirmation and redirects to the StoreIndex view.
        // If the store with the given id is not found, no action is taken.
        // Otherwise, the store is removed from the database and the StoreIndex view is returned.
        [HttpPost, ActionName("DeleteStore")]
        public IActionResult ConfirmDeleteStore(Guid id)
        {
            CheckLogin();
            Store selectedStore = _context.Stores.Find(id);
            if (selectedStore != null)
            {
                _context.Stores.Remove(selectedStore);
                _context.SaveChanges();
            }
            return RedirectToAction("StoreIndex");
        }

    }
}

Views/Access/HomePage.cshtml
@using Project_C.Models.UserModels;

@{
    bool IsLoggedIn = false;
    bool IsAdmin = false;


    if(Project_C.Models.UserModels.CurrentEmployee.currentEmployee != null)
    {
        IsLoggedIn = true;
        if (Project_C.Models.UserModels.CurrentEmployee.currentEmployee.IsAdmin == true)
        {
            IsAdmin = true;
        }
    }
    }
<head>
<link rel="stylesheet" href="~/css/adminhome.css">
</head>
<body>
    <div class="welkomtekst">Welkom @CurrentEmployee.currentEmployee.Username </div>
    <div class="lines_product2"></div>
    <div class="lines_product"></div>
    <div class="lines_product3"></div>
    <div class="lines_product4"></div>
    
    <div class="navigation">
        <ul>
            @{
                if (IsLoggedIn)
                {
                    <bi>
                    <span class="heart">
                     <ion-icon name="heart-outline"></ion-icon>
                </span>
                        <span class="middleline">
                            <ion-icon name="heart-outline"></ion-icon>
                        </span>
            </bi>
           
                    <li>
                    <a asp-action="ProductIndex" asp-controller="Product" class="Producten">
                        
                        <span class="icon">
                                <div href="/"><img src="~/images/producten.png"></div>
                        </span>
                            <span class="text">Producten </span>

                        </a>
                    </li>

                    <win>
                    <a asp-action="StoreIndex" asp-controller="Store" class="Winkels">
                        
                        <span class="icon">
                                <div href="/"><img src="~/images/winkel.png"></div>
                            
                        </span>
                            <span class="text">Winkels</span>
                        
                    </a>
                    </win>

                    <lit>
                    <a asp-action="Logout" asp-controller="Access" class="Uitloggen">
                        
                        <span class="icon">
                            <ion-icon name="log-out-sharp"></ion-icon>
                        </span>
                            <span class="text">Uitloggen</span>

                        </a>
                    </lit>
                    <be>
                    <a asp-action="MessageIndex" asp-controller="Message" class="Uitloggen">
                                        <span class="icon">
                                
                                <ion-icon name="mail-open-sharp"></ion-icon>
                        </span>
                            <span class="text">Berichten</span>
                            </a>
                    </be>
                            if (IsAdmin)
                            {
                                <med>
                                <a asp-action="EmployeeIndex" asp-controller="Employee" class="Medewerker">
                                    
                                     <span class="icon">
                                    <div href="/"><img src="~/images/admin.png"></div>
                                        </span>
                                <span class="text">Medewerkers</span>

                            </a>
                                </med>
                        <div class="index3"></div>
                            }
                        }
                    
                }
            <div class="index"></div>
            <div class="index1"></div>
            <div class="index2"></div>
            <div class="heartline"></div>
            
        </ul>
        <b class="logo" href="/"><img src="~/images/Sol.png"></b>
    </div>


<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>

Views/Access/LoginPage.cshtml
@model Project_C.Models.UserModels.LoginCredentials


<logdiv> 
    <div class="bkg"></div>
   
   
    
<div class="container">
    <div class="col-md-4">
        <link rel="stylesheet" href="~/css/loginpage.css">  
        <form method="post" enctype="multipart/form-data" asp-action="LoginPage" asp-controller="Access">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="email-group">
                <label asp-for="Email" class="control-label">E-mail</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="password-group">
                <label asp-for="Password" class="control-label">Wachtwoord</label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
                <a class="LogIn">
                    <input type="submit" value="Inloggen" class="btn btn-success" />
                </a>
        </form>
    </div>
</div>

</logdiv>
<b class="logo" href="/"><img src="~/images/icon-admin.png"></b>
<div class="logobkg"></div>